FROM bcgovimages/aries-cloudagent:py36-1.16-1_0.7.0rc0
#FROM bcgovimages/aries-cloudagent:py36-1.14-1_0.5.1

USER root
RUN apt-get update
RUN apt-get update && apt-get install -y gcc



ADD https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 ./jq
RUN chmod +x ./jq
COPY scripts/startup-prod.sh startup.sh
RUN chmod +x ./startup.sh


USER $user

ENTRYPOINT ["/usr/bin/env"]
CMD bash startup.sh